### ISSUE TITLE
Wildcard route gobbles up all traffic

### ISSUE THREAD

**Issue by macdonst** [enhance-dev/arc-plugin-enhance#1]
To reproduce, create two new pages:

```
begin new page -p '/books/$id' -t js
begin new page -p '/books/new' -t js
```

Then if you go to `http://localhost:3333/books/8974` you get the `$id` page but if you go to  `http://localhost:3333/books/new` you still get the `$id` page.

**Comment by macdonst** [comment]
It gets more complicated when you have routes that don't end in a wildcard like:

```
/books
/books/new
/books/$id
/books/$id/delete
```

**Comment by brianleroux** [comment]
should be fixed in latest / lmk if it works for you

**Comment by macdonst** [comment]
Perfect, thx!
