### ISSUE TITLE
Url encoding keys for CRUD scaffolds?

### ISSUE THREAD

**Issue by hovissimo** [enhance-dev/arc-plugin-enhance#13]
I mentioned this in the Discord ([link to message](https://discord.com/channels/1012099764713705472/1012435743571988560/1019623063370858616)). @brianleroux asked for an issue against this project.

When I tried to use a base64 string as the key for one of my crud records, I couldn't delete it due to a 404 error.

I got it to work after url-encoding the key.

https://github.com/hovissimo/urlencoded_key includes a reproduction and a "fix".

I generated that project with 
`npm create @enhance ./urlencoded_key` and then `begin generate scaffold Thingy`

0. (https://discord.com/channels/1012099764713705472/1012435743571988560/1019623063370858616)

**Comment by brianleroux** [comment]
ah! I get it now, ok, this would be expected behaviour as the base64 left both `/` and `=` in the value which are def URL sensitive; worth mentioning the begin/data package will create url safe keys for you (set a value without a `key` and it'll create one in the return value)
