### ISSUE TITLE
Setting cache control on API routes works when passed via `headers`, but not via `cacheControl` shortcut

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/arc-plugin-enhance#74]
As of 5.0.3, setting cache control as follows works correctly:

```js
export async function get () {
  return {
    headers: {
      'cache-control': 'max-age=<time>`',
    }
  }
}
```

However, using the [`cacheControl` shortcut](https://arc.codes/docs/en/reference/runtime-helpers/node.js#responses) does not set the cache control correctly in the response headers:

```js
export async function get () {
  return {
    cacheControl: 'max-age=<time>',
  }
}
```

**Comment by kristoferjoseph** [comment]
@cole is this reproduction example correct?
`cacheControl` needs to be a string.

```javascript
export async function get () {
  return {
    'cacheControl': 'max-age=<time>',
  }
}
```
Was this a typo?

**Comment by colepeters** [comment]
Whoa, throwback! Haha. I think it must've been! This was still early in my time working w/ these headers so that's very likely :D
