### ISSUE TITLE
Requesting files larger then 6mb from /_public results in an error

### ISSUE THREAD

**Issue by macdonst** [enhance-dev/arc-plugin-enhance#79]
The largest payload we can return from a lambda is 6mb. We should check to see how large the file is before we start to stream the response. If greater than 6mb we should redirect to the fingerprinted /_static route.

**Comment by kristoferjoseph** [comment]
Is this fixed now?

**Comment by macdonst** [comment]
Yes, I'm pretty sure this is all wrapped up with https://github.com/enhance-dev/arc-plugin-enhance/commit/2a68816e986f3527741e6aec777dbab2622c55de
