### ISSUE TITLE
Errors are missing line numbers, stack trace, or other useful hints

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/arc-plugin-enhance#81]
Errors from Enhance SSR don't currently mention the line number or file where an error occurred, not do they provide a stack trace.

**Reproduction:** https://github.com/colepeters/enhance-error-repro

For example, given an error in a function within an SFC (in the repro above, passing an undefined value to a function expecting a string to perform a `.split()` on), the error provided in the browser is:

```
Oops, something went wrong
Cannot read properties of undefined (reading 'split')
```

Can we make these errors more helpful?

**Comment by kristoferjoseph** [comment]
The error is indeed available but only the error message is being passed to the 500 page.
https://github.com/enhance-dev/arc-plugin-enhance/blob/main/src/http/any-catchall/router.mjs#L194

I am looking at outputting the entire error to the body of the 500 page.
