### ISSUE TITLE
Projects with incompatible external dependencies in `package[-lock].json` may result in broken Enhance apps

### ISSUE THREAD

**Issue by ryanblock** [enhance-dev/arc-plugin-enhance#87]
Today we found an issue with an Enhance app that contained a `package-lock.json` file that specified an incompatible external dependency. Once deployed, the app immediately stopped functioning.

What happened under the hood: during Lambda treeshaking of the [`any /*` handler](https://github.com/enhance-dev/arc-plugin-enhance/tree/main/src/http/any-catchall), Architect Hydrate found a specific (and incompatible) version of an imported dependency in the root `package-lock.json` file. It installed that version, which then broke the handler.

The particular dependency in question was `glob`, but this could happen to any of Enhance's external deps; for example, if a user had specified an older, incompatible version of [`@enhance/import-transform`](https://github.com/enhance-dev/enhance-import-transform) in their `package[-lock].json` files, the result would have been the same.

The only way to ensure `arc-plugin-enhance` Lambdae will have the exact external dependencies it needs is to specify them in a `package.json` file within each handler (e.g. `src/http/any-catchall/package.json`).

**Comment by kristoferjoseph** [comment]
Fixed in v9.4.3
