### ISSUE TITLE
Expand README to describe how to integrate enhance into an existing arc app

### ISSUE THREAD

**Issue by filmaj** [enhance-dev/arc-plugin-enhance#91]
Hello! I am curious to give enhance a try in my pre-existing arc app that is mainly a ton of Dynamo tables and scheduled and SNS events. I have a couple of existing `@http` definitions in this arc app but they are extremely barebones and are nothing more than super basic dynamo DB state views. I am planning on adding a more complete web frontend so I wanted to experiment to see how building such a frontend with enhance would work.

However, I am having trouble getting going. I think I am stumbling upon some basic stuff that neither the README nor [enhance architect migration docs](https://enhance.dev/docs/learn/practices/architect-migration) cover. Here are some of my "enhance noobie" perspectives/questions/confusions that may be helpful in re-evaluating this plugin's README and/or the enhance arc migration docs:

- It would be cool to put technical instructions on how to integrate enhance into an existing arc project directly in this README. A kind of architect-centric approach/description. Instead, this readme links to the main enhance docs, and the enhance docs are not built from the perspective of an architect user, but rather target a broader audience. Given this project is an architect plugin, I think it would help if this project provided installation and quickstart instructions from an architect perspective.
- What are the knowledge/concept prerequisites I should have before following [the Migration doc](https://enhance.dev/docs/learn/practices/architect-migration)? Should I read the entire enhance docs first before following the migration guide? I think any such pre-reqs should be explicitly listed at the top of the migration doc.
- This note in the migration doc is concerning to me: "If Begin Data is used the table definition should be removed before the Enhance plugin is added. Begin data is included with Enhance and defining these tables in two places can cause problems." So if I use Begin Data I need to remove it - OK, I don't use Begin Data in my arc app, so I think I'm ok? But then the next sentence says Begin Data is included in Enhance - so if I use Enhance I _will_ be using Begin Data? 😕 😣 i haz a confuse. My current plan is to read this plugin's source code front-to-back to understand what I am adding to my arc app better. It would be nice to instead summarize these additions in the project's README.
- The final step in the 'complete arc migration' says "Move each handler into the file base routing app/api and app/pages folders and then remove the corresponding route definition in the arc file." Can we also add an additional step after this that hand-holds readers through verifying everything works as desired? Should I run an `enhance` CLI command to test everything? Should I run `arc sandbox` instead? I, perhaps foolishly, but I am just a noobie getting my bearings, tried running `arc create` thinking the plugin would create these `app/*` folders for me, but no such thing happened, so I decided not to run any commands further until I a) read the source code front to back for this plugin and b) filed this issue 😄 

If someone can talk me through these confusions and help me understand how this plugin works better, I am happy to send a PR to update the README and/or enhance docs.

**Comment by kristoferjoseph** [comment]
I feel a lot of your questions can be answered by explaining that Enhance is a culmination of all the feedback from users that found Architect to be too much like a toolbox that was dumped out on a table.

Enhance wraps most Architect concepts - DynamoDB, routes, etc. and enables these through higher level constructs of pages, elements, api. So you should not expect to use Architect commands with Enhance.

Enhance is meant to be a batteries included app framework built on top of Architect so even though it uses arc plugins it is not much like a default Architect project.

I would encourage you to go through the [quickstart](https://enhance.dev/docs/) and learn Enhance if you want to get all the benefits it supplies and not think of it as an Architect project but as an Enhance project. You will however be able to reuse your lower level Architect knowledge of plugins and how everything works one deployed.

As for your questions:
1. We added the Architect migration doc for this purpose. Without learning how Enhance is meant to be first the Architect integration in the README would be confusing for first time Enhance users. It is much easier to create an Enhance project and add Arc plugins to it than to try and add the Enhance plugin to an existing Architect project and expect it to work as it was previously. Enhance creates a catch-all route and looks up frontend primitives in specific directories for you. If everything it put in the expected directory things just work. You would need to refactor your Architect project to move primitives into expected directories. Basically adding Architect specific docs to the Enhance plugin README is inappropriate and would make things harder.
2. I would encourage you to go through the [quickstart](https://enhance.dev/docs/)
3. The Enhance is setup to use DynamoDB with Begin data out of the box. The Enhance plugin preconfigures your Begin data table so you could have arc tables that are incompatible or in conflict in an existing Architect app. I would do a test run in a branch and make a throw away deploy to see what I mean here.
4.The final step is just navigating to the different "pages" in the pages directory. No need to run any commands other than `npm start`. [Read up on how pages are mapped here](https://enhance.dev/docs/learn/starter-project/pages) 

There will be things you use Architect for that are not bundles into Enhance, but there are **a lot** of features baked into Enhance that were really difficult to do in a barebones Architect app so starting with an Enhance app then adding in the Architect service plugins would be my recommendation. Making an arc app and adding the Enhance plugin would not do what you expect, especially if you haven't familiarized yourself with Enhance at all.
